---
name: Debian Slim Images

on:
  push:
    tags:
      - "[0-9].[0-9].[0-9]"

jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      FLAVOUR: slim
    steps:
      - name: Checkout Dockerfiles and Context
        uses: actions/checkout@v2

      - id: get_data
        uses: ./.github/actions/get-data
        with:
          flavour: ${{ env.FLAVOUR }}

      - id: get_labels
        uses: ./.github/actions/get-labels
        with:
          title: 'Etebase Server'
          authors: 'Victor R. Santos <victor-rds@users.noreply.github.com>'
          version: ${{ steps.get_data.outputs.version }}-${{ env.FLAVOUR }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.1.0
        with:
          platforms: amd64,arm64,arm

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Login to DockerHub
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push
        id: docker_build_push
        uses: docker/build-push-action@v2.6.1
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          context: .
          file: ./tags/${{ env.FLAVOUR }}/Dockerfile
          build-args: ETE_VERSION=v${{ steps.get_data.outputs.version }}
          labels: ${{ steps.get_labels.outputs.labels }}
          tags: ${{ steps.get_data.outputs.tags }}
          push: true