name: Build Slim Tag on Pull Requests

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'context/**'
      - 'tags/slim/Dockerfile'

jobs:
  build-slim:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: victorrds/etesync
        always_pull: true
        add_git_labels: true
        push: false
        dockerfile: ./tags/slim/Dockerfile
        tags: ${{ github.sha }}-slim
        build_args: TAG=master